# Generated by Django 4.2.30 on 2026-06-05 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server_connections', '0002_fix_eapauthentication_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IKEv2PSK',
            fields=[
                ('connection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='server_connections.connection')),
            ],
            bases=('server_connections.connection',),
        ),
        migrations.CreateModel(
            name='PskAuthentication',
            fields=[
                ('authentication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='server_connections.authentication')),
                ('psk', models.TextField(default='')),
                ('identity', models.TextField(blank=True, default='')),
            ],
            bases=('server_connections.authentication',),
        ),
    ]
